site_name: Swytch Docs
site_url: https://mydomain.org/mysite

nav:
  - Home: index.md 
  - Getting started: 
      - Installation: Installation.md
      - Quickstart: Quickstart.md
  - Guide: Guide.md
  - Release Notes: ReleaseNotes.md
  - Help: Help.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite        
        
theme:
  name: material
  logo: img/logo-5.png
  favicon: img/logo-5.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
    
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: grey
      accent: green
  features:
    - content.code.copy
    
    
  font:
    text: "Open Sans"
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github  
extra:
  generator: false
  
repo_url: https://github.com/Gwali-1/Swytch/blob/main/Notes/notes.md


    
