site_name: Swytch Docs
docs_dir: docs
site_dir: ../site
site_url: https://gwali-1.github.io/Swytch
use_directory_urls: false


nav:
  - Home: index.md 
  - Getting started: 
      - Installation: Installation.md
      - Quickstart: Quickstart.md
  - Guide:
      - General: Guide.md
      - Swytch templates: SwytchTemplates.md
      - RequestContext: RequestContext.md
      - Authentication Utilities:  AuthUtility.md
      - Swytch ActorPool:  ActorPool.md
      
  - Release Notes: ReleaseNotes.md
  - Help: Help.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite        
        
theme:
  name: material
  logo: img/logo-5.png
  favicon: img/logo-5.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
   
    
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: grey
      accent: green
  features:
    - content.code.copy
    
    
  font:
    text: "Open Sans"
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github  
extra:
  generator: false
  base_url: /Swytch/

repo_url: https://github.com/Gwali-1/Swytch/blob/main/Notes/notes.md


    
